
[settle]
  auto_deposit_interval = 3
  check_deposit_interval = 2
  check_tx_interval = 4
  collect_interval = 10
  collect_utxo_threshold = 3
  force_collect_amount_times = 5
  force_collect_interval = 50
  opcu_asset_distributioon = [50, 25, 15, 10]
  opcu_asset_transfer_interval = 5
  pre_key_gen_interval = 100
  process_order_interval = 3
  sync_gas_interval = 10
  systransfer_interval = 4
  withdraw_interval = 6
